openapi: 3.0.0
info:
  title: Feed API
  description: API for retrieving posts and projects feeds
  version: 1.0.0

paths:
  /feed/posts:
    get:
      summary: Retrieve posts feed
      description: Fetches a list of posts sorted by time or likes
      parameters:
        - in: query
          name: type
          required: true
          schema:
            type: string
            enum: 
              - time
              - likes
          description: Sorting type for the feed (by time or likes)
        - in: query
          name: start
          required: true
          schema:
            type: integer
            minimum: 0
          description: Starting index for pagination
        - in: query
          name: count
          required: true
          schema:
            type: integer
            minimum: 1
          description: Number of posts to retrieve
      responses:
        '200':
          description: Successful retrieval of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '400':
          description: Bad request (missing or invalid parameters)
        '404':
          description: Not found
        '500':
          description: Internal server error

  /feed/projects:
    get:
      summary: Retrieve projects feed
      description: Fetches a list of projects sorted by time or likes
      parameters:
        - in: query
          name: type
          required: true
          schema:
            type: string
            enum: 
              - time
              - likes
          description: Sorting type for the feed (by time or likes)
        - in: query
          name: start
          required: true
          schema:
            type: integer
            minimum: 0
          description: Starting index for pagination
        - in: query
          name: count
          required: true
          schema:
            type: integer
            minimum: 1
          description: Number of projects to retrieve
      responses:
        '200':
          description: Successful retrieval of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
        '400':
          description: Bad request (missing or invalid parameters)
        '404':
          description: Not found
        '500':
          description: Internal server error

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user:
          type: integer
          format: int64
        project:
          type: integer
          format: int64
        likes:
          type: integer
          format: int64
        content:
          type: string
        created_on:
          type: string
          format: date-time

    Project:
      type: object
      properties:
        id:
          type: integer
          format: int64
        owner:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        status:
          type: integer
          format: int16
        likes:
          type: integer
          format: int64
        tags:
          type: array
          items:
            type: string
        links:
          type: array
          items:
            type: string
        creation_date:
          type: string
          format: date-time
