openapi: 3.0.0
info:
  title: Project API
  description: API for managing project records, including fetching, creating, updating, and deleting projects.
  version: 1.0.0
paths:
  /projects/{project_id}:
    get:
      summary: Get project by ID
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Project details retrieved successfully
        '400':
          description: Invalid project ID
        '404':
          description: Project not found
        '500':
          description: Internal server error
    delete:
      summary: Delete project by ID
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Project deleted successfully
        '400':
          description: Invalid project ID
        '404':
          description: Project not found
        '500':
          description: Internal server error
    put:
      summary: Update project information
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Project updated successfully
        '400':
          description: Invalid input or disallowed fields
        '404':
          description: Project not found
        '500':
          description: Internal server error

  /projects/by-user/{user_id}:
    get:
      summary: Get projects by user ID
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Projects retrieved successfully
        '400':
          description: Invalid user ID
        '404':
          description: User not found
        '500':
          description: Internal server error

  /projects:
    post:
      summary: Create new project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '201':
          description: Project created successfully
        '400':
          description: Invalid input or owner verification failed
        '500':
          description: Internal server error

  /projects/{project_id}/followers:
    get:
      summary: Get project followers
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Followers retrieved successfully
        '400':
          description: Invalid project ID
        '500':
          description: Internal server error

  /projects/{project_id}/followers/usernames:
    get:
      summary: Get project followers' usernames
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Follower usernames retrieved successfully
        '400':
          description: Invalid project ID
        '500':
          description: Internal server error

  /projects/follows/{username}:
    get:
      summary: Get projects followed by user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Following projects retrieved successfully
        '404':
          description: User not found
        '500':
          description: Internal server error

  /projects/follows/{username}/names:
    get:
      summary: Get names of projects followed by user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project names retrieved successfully
        '404':
          description: User not found
        '500':
          description: Internal server error

  /projects/{username}/follow/{project_id}:
    post:
      summary: Follow a project
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project followed successfully
        '404':
          description: Project or user not found
        '500':
          description: Internal server error

  /projects/{username}/unfollow/{project_id}:
    post:
      summary: Unfollow a project
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project unfollowed successfully
        '404':
          description: Project or user not found
        '500':
          description: Internal server error

  /projects/{username}/likes/{project_id}:
    post:
      summary: Like a project
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project liked successfully
        '404':
          description: Project or user not found
        '500':
          description: Internal server error

  /projects/{username}/unlikes/{project_id}:
    post:
      summary: Unlike a project
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project unliked successfully
        '404':
          description: Project or user not found
        '500':
          description: Internal server error

  /projects/does-like/{username}/{project_id}:
    get:
      summary: Check if project is liked by user
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: integer
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Like status retrieved successfully
        '404':
          description: Project or user not found
        '500':
          description: Internal server error

components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: integer
          format: int64
        owner:
          type: integer
          format: int64
          description: ID of the user who owns the project.
        name:
          type: string
        description:
          type: string
        status:
          type: integer
          format: int16
        likes:
          type: integer
          format: int64
        tags:
          type: array
          items:
            type: string
        links:
          type: array
          items:
            type: string
        created_on:
          type: string
          format: date-time
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
