openapi: 3.0.0
info:
  title: User Management API
  description: API for managing user records, including fetching, creating, updating, and deleting users.
  version: 1.0.0
paths:
  /users/{username}:
    get:
      summary: Get user by username
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User retrieved successfully
        '404':
          description: User not found
        '500':
          description: Internal server error
    delete:
      summary: Delete user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User deleted successfully
        '404':
          description: User not found
        '500':
          description: Internal server error
    put:
      summary: Update user information
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Invalid input or disallowed fields
        '404':
          description: User not found
        '500':
          description: Internal server error

  /users:
    post:
      summary: Create new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /users/{username}/followers:
    get:
      summary: Get user's followers
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Followers retrieved successfully
        '404':
          description: User not found
        '500':
          description: Internal server error

  /users/{username}/following:
    get:
      summary: Get users followed by user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Following users retrieved successfully
        '404':
          description: User not found
        '500':
          description: Internal server error

  /users/{username}/followers/usernames:
    get:
      summary: Get usernames of user's followers
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Follower usernames retrieved successfully
        '404':
          description: User not found
        '500':
          description: Internal server error

  /users/{username}/following/usernames:
    get:
      summary: Get usernames of users followed by user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Following usernames retrieved successfully
        '404':
          description: User not found
        '500':
          description: Internal server error

  /users/{username}/follow/{new_follow}:
    post:
      summary: Follow a user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
        - name: new_follow
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User followed successfully
        '400':
          description: Invalid operation or already following
        '500':
          description: Internal server error

  /users/{username}/unfollow/{unfollow}:
    delete:
      summary: Unfollow a user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
        - name: unfollow
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User unfollowed successfully
        '400':
          description: Invalid operation or not following
        '500':
          description: Internal server error

components:
  schemas:
    User: # this references the User type in internal/types/types.gp
          # however, should be sent as a JSON, obv
      type: object
      properties:
        username:
          type: string
        bio:
          type: string
        links:
          type: array
          items:
            type: string
        created_on:
          type: string
          format: date-time
        picture:
          type: string
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
